### PR TITLE
Fix missing space (causes sudo npm -g installpackagename)

### PR DESCRIPTION
**Pull request by dxdc**

### CODE REVIEW

**Comment by DenizOkcu** [comment]
Thank you! Just found the same issue 👍

**Comment by Snaptags** [comment]
Thank you for this PR, I just noticed it, too.

**Comment by Sgryt87** [comment]
Just had that issue but saw your PR with the fix. Thank you.

**Comment by raineorshine** [comment]
Thanks everyone!

**Comment by raineorshine** [comment]
Published in `v7.1.1`

**Pull request merged**
