### PR TITLE
Added dev-only flag (-d, --dev) and prod-only (-p, --prod) flag

### LINKED ISSUE #36: [Request] --dev
Would it be complicated to add support for dev deps as well ?

### PR DESCRIPTION
**Pull request by nitriques**
This will allow developers to make the check a little bit faster and a bit safer when dealing with only devDeps.

Fixes #36

I could not resists doing it, it was too simple to implement!!

### CODE REVIEW

**Comment by tjunnone** [comment]
Sorry for the delay. 1.5.0 is now published

**Comment by nitriques** [comment]
Thanks !

**Comment by fxalgrain** [comment]
Updated :) 
Thanks !

**Comment by nitriques** [comment]
```
$ npm-check-updates -g

"npm-check-updates" can be updated from 1.3.0 to 1.5.0
```

:100:

**Pull request merged**
