### PR TITLE
fix: Fix ignore .ncurc.yml settings for --deep option

### PR DESCRIPTION
**Pull request by art-ws**
#826

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks! Could we get a test?

**Comment by art-ws** [comment]
> Thanks! Could we get a test?

Not sure we have a time for it:) Just forked and using a fixed version for a while. 
Although fix is too simple, but test implementation for such core feature better to implement by core team as you understand all details and bound cases much more better than random contributor.

**Comment by raineorshine** [comment]
Cool. Shouldn’t be too hard. Thanks!

**Comment by raineorshine** [comment]
Published in `v11.4.1`

**Pull request merged**
