### PR TITLE
fix: programmatic usage README

### PR DESCRIPTION
**Pull request by Netail**
In v17 the run command is exported per default :)

### CODE REVIEW

**Comment by Netail** [comment]
nvm, in favour of #1410 lol

**Comment by raineorshine** [comment]
Actually, #1410 broke the verdaccio integration test, so I had to revert. 

I'm still not sure how to properly switch to a default export, as it worked for some people but not others.

**Comment by Netail** [comment]
Oh interesting, the default export with `17.0.0-6` worked for me

**Comment by raineorshine** [comment]
Yes, it's been elusive. 

Ultimately I want just the default export, not a named export.

Related: #1199, #1404

**Pull request closed without merging**
