### PR TITLE
Switch to GitHub Actions CI

### PR DESCRIPTION
**Pull request by XhmikosR**
@raineorshine some notes:

1. I didn't add npm cache but it's easy to add if you need it later
2. Runs on Linux and Windows
3. I kept your branches Travis CI config: only runs on master and all PRs
4. I had to modify the npm scripts a bit
5. Before merging this, you should remove Travis CI from the repository apps/integrations/hooks

For security reasons this won't run now, only after it's merged (so the badge is expected to be broken). Here's a previous run on my fork: <https://github.com/XhmikosR/npm-check-updates/actions/runs/105717586>

PS. Are you sure you need snyk? Have you enabled [automated security fixes](https://help.github.com/en/github/managing-security-vulnerabilities/configuring-automated-security-updates#managing-automated-security-updates-for-your-repository) in the repo and delete `HEAD` branches automatically?

### CODE REVIEW

**Comment by raineorshine** [comment]
> For security reasons this won't run now, only after it's merged (so the badge is expected to be broken). Here's a previous run on my fork: https://github.com/XhmikosR/npm-check-updates/actions/runs/105717586

Thanks, I'll give it a try!

> 
> PS. Are you sure you need snyk? 

No, is it not needed any longer? It seemed like a good idea at the time.

> Have you enabled [automated security fixes](https://help.github.com/en/github/managing-security-vulnerabilities/configuring-automated-security-updates#managing-automated-security-updates-for-your-repository) in the repo and delete `HEAD` branches automatically?

Yes!

**Comment by XhmikosR** [comment]
It's your call if you want to keep snyk. I personally don't use it, just automated security fixes and npm audit. You could probably even add npm audit on CI and make the build fail if you want to.

Not directly related to this PR, it's just that it would simplify the 2 scripts and you'd have only one. But you can tackle this later if you want to. 🙂

**Comment by raineorshine** [comment]
I trust your judgment. If you'd like to remove it in this PR that'd be fine. Thank you!

**Comment by XhmikosR** [comment]
>I trust your judgment. If you'd like to remove it in this PR that'd be fine. Thank you!

😳

Maybe it'd be better to do it in a separate PR to keep things clean?

**Comment by XhmikosR** [comment]
Actually, now that I think about it, we could probably ditch cross-env and just set `process.env.NODE_ENV = 'test'` in test-ncu.js. Minus one package, always better :)

I'll push that here and then you review and merge if you are OK with what I've pushed so far.

**Pull request merged**
