### PR TITLE
package.json: fix `lint:markdown` script

### PR DESCRIPTION
**Pull request by XhmikosR**
Single quotes don't work on all platforms

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks :)

**Comment by XhmikosR** [comment]
Might be worth looking at https://github.com/DavidAnson/markdownlint-cli2 later too :)

**Comment by raineorshine** [comment]
> Might be worth looking at [DavidAnson/markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2) later too :)

I looked briefly. It had fewer stars and less recent updates so I want with the main cli.

**Comment by XhmikosR** [comment]
TBH this one is the newer cli made by the creator of markdowlint. He maintains both packages, but cli2 is a lot faster. Your call, I personally have switched to cli2 and it works like a charm, but it has a few fundamental differences.

**Comment by raineorshine** [comment]
Thanks, I'll keep that in mind.

**Pull request merged**
