### PR TITLE
Doctor mode

### PR DESCRIPTION
**Pull request by raineorshine**
Add `--doctor` option to iteratively install upgrades and run tests to identify breaking upgrades.

```sh
$ ncu --doctor
npm install
npm run test
ncu -u
npm install
npm run test
Failing tests found:
/Users/raine/projects/npm-check-updates/test/doctor/fail/test.js:13
  throw new Error('foo')
  ^
Now let's identify the culprit, shall we?
Restoring package.json
Restoring package-lock.json
npm install
npm install ncu-test-v2@2.0.0
npm run test
  ✓ ncu-test-v2 1.0.0 → 2.0.0
npm install ncu-test-return-version@2.0.0
npm run test
  ✗ ncu-test-return-version 1.0.0 → 2.0.0
```

### CODE REVIEW

**Comment by raineorshine** [comment]
@XhmikosR I'm really excited to add this new feature, but something's wrong with the output on Windows. Would you possibly be able to take a look? Would be a big help!

**Comment by stoically** [comment]
Excellent addition, thanks for working on this!

**Comment by gabriel-kohen-by** [comment]
I love this one. Can we configure additional tasks to run on --doctor mode? test task is obvious but we have some breaks during the actual tasks build.
Thank you.

**Comment by raineorshine** [comment]
> I love this one. Can we configure additional tasks to run on --doctor mode? test task is obvious but we have some breaks during the actual tasks build.
> Thank you.

@gabriel-kohen-by Good idea! Perhaps an option for doctor to run an arbitrary npm script?

```
ncu -u --doctor --doctor-test foo
```

**Pull request merged**
