### PR TITLE
Support doctorTest command that includes quotes

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**
Related to #1259 but probably doesn't really close it, as it only acts as a workaround for running multiple commands

"global should run" test failed for me both with and without my changes (I didn't forget to rebuild)

### CODE REVIEW

**Comment by Maxim-Mazurok** [comment]
I'll check test failures on the CI and address the issues later

**Comment by raineorshine** [comment]
Thanks!

I think it would be better to use only simple, built-in shell functions rather than invoking npx or npm in the test.

**Comment by Maxim-Mazurok** [comment]
Agree, just couldn't think of a better way to test it on both Windows and Linux.
Now will be running a simple node script, which should work much faster and better.

**Comment by Maxim-Mazurok** [comment]
Hopefully fixed failing tests

**Review by raineorshine — APPROVED** [review]

**Pull request merged**
